"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.steps = void 0;
exports.workingStep = workingStep;
exports.working = working;
const study_1 = require("../model/study");
const validation_1 = require("../model/validation");
const common_1 = require("./common");
exports.steps = ['Loads & resultants', 'Support reactions', 'Region equations', 'Shear force', 'Bending moment', 'Critical values'];
function workingStep(m, a, n) {
    const actual = (0, study_1.effectiveModel)(m);
    const effectiveActions = [...actual.items.filter(i => (0, validation_1.isLoad)(i.kind)), ...(actual.internalDistributedLoads || [])];
    if (n === 0)
        return `<h3>Reduce the loading, without losing its moment.</h3><p>These are the <b>effective actions</b> after active case factors and optional self-weight. True stepped sections contribute their own local self-weight intensity. Distributed loading is integrated exactly, not replaced by little point loads in the solver.</p><div class="table-scroll"><table><thead><tr><th>Action</th><th>Range / position</th><th>Net force</th><th>Acts at x</th></tr></thead><tbody>${effectiveActions.map(i => { const r = (0, study_1.resultant)(i); return `<tr><td><i style="background:${i.colour}" class="dot"></i>${(0, common_1.esc)(i.label)}</td><td>${(0, common_1.fmt)(i.x)}${i.end !== undefined ? ' to ' + (0, common_1.fmt)(i.end) : ''} m</td><td>${i.kind === 'moment' ? (0, common_1.signed)(i.value) + ' kN·m (CCW)' : (0, common_1.signed)(r.force) + ' kN'}</td><td>${i.kind === 'moment' ? 'Couple / no net force' : r.position === null ? 'No single force resultant' : (0, common_1.fmt)(r.position) + ' m'}</td></tr>${r.position === null && Math.abs(r.firstMoment) > 1e-8 ? `<tr><td colspan="4">Zero net force, but first moment = ${(0, common_1.signed)(r.firstMoment)} kN·m. Do not discard this loading.</td></tr>` : ''}`; }).join('')}</tbody></table></div><div class="formula">W = ∫ w(x) dx &nbsp;&nbsp; x̄ = ∫ xw(x) dx / W</div><p class="muted">The resultant position formula is undefined when W = 0. The solver still retains the distributed action and its first moment.</p>`;
    if (n === 1)
        return `<h3>Apply the restraints, then check equilibrium.</h3><div class="equations"><div>ΣRᵧ = ${(0, common_1.fmt)(a.reactions.reduce((s, r) => s + r.force, 0), 4)} kN = ${(0, common_1.fmt)(a.total, 4)} kN downward load</div><div>Σ(Rᵧx + reaction couples) − load first moments + applied CCW couples = 0</div></div><p>For a continuous or restrained beam, equilibrium alone does not determine the reactions. BeamLab solves <b>K<sub>ff</sub>d<sub>f</sub> = F<sub>f</sub> − K<sub>fc</sub>d<sub>c</sub></b>, where <b>d<sub>c</sub></b> contains any prescribed support settlements and fixed-support rotations, using compatibility and the EI assigned to each event-aligned beam element. It then recovers the reactions. Hinges share vertical displacement but release rotation.</p><div class="table-scroll"><table><thead><tr><th>Support</th><th>x / m</th><th>Settlement / mm</th><th>Rotation / mrad</th><th>Rᵧ / kN</th><th>CCW couple / kN·m</th></tr></thead><tbody>${a.reactions.map(r => `<tr><td>${(0, common_1.esc)(r.label)}</td><td>${(0, common_1.fmt)(r.x)}</td><td>${(0,common_1.signed)(r.settlementMm || 0,3)}</td><td>${(0,common_1.signed)(r.rotationMrad || 0,3)}</td><td>${(0, common_1.signed)(r.force, 5)}</td><td>${(0, common_1.signed)(r.moment, 5)}</td></tr>`).join('')}</tbody></table></div><p class="muted">Force residual ${a.forceResidual.toExponential(2)} kN / moment residual ${a.momentResidual.toExponential(2)} kN·m.</p>`;
    if (n === 2)
        return `<h3>Write a local equation for each region.</h3><p>Let t = x − region start. With downward intensity positive, <b>V(t) = V₀ − w₀t − kt²/2</b> and <b>M(t) = M₀ + V₀t − w₀t²/2 − kt³/6</b>.</p><div class="regions">${a.elements.map(e => `<article><b>${(0, common_1.fmt)(e.a, 3)} to ${(0, common_1.fmt)(e.b, 3)} m</b><small>${(0,common_1.esc)(e.sectionRegionLabel || 'Base section')} · ${(0,common_1.esc)(e.sectionLabel || 'section')} · EI ${(0,common_1.fmt)(e.EI/1000,3)} MN·m²${Math.abs((e.stiffnessFactor||1)-1)>1e-12?' · EI-only ×'+(0,common_1.fmt)(e.stiffnessFactor,3):''}</small><code>w(t) = ${(0, common_1.fmt)(e.w0, 5)} + (${(0, common_1.fmt)(e.slope, 5)})t</code><code>V(t) = ${(0, common_1.fmt)(e.r[0], 5)} - (${(0, common_1.fmt)(e.w0, 5)})t - (${(0, common_1.fmt)(e.slope / 2, 5)})t²</code><code>M(t) = ${(0, common_1.fmt)(-e.r[1], 5)} + (${(0, common_1.fmt)(e.r[0], 5)})t - (${(0, common_1.fmt)(e.w0 / 2, 5)})t² - (${(0, common_1.fmt)(e.slope / 6, 5)})t³</code></article>`).join('')}</div>`;
    if (n === 3)
        return `<h3>Loading changes the slope of the shear diagram.</h3><div class="formula">dV/dx = −w(x)</div><p>Between actions, a point-free, unloaded region has constant shear. Uniform loading gives a straight shear slope. Linear loading gives a quadratic shear curve.</p><p>A downward point force P jumps the shear by <b>−P</b>. An upward reaction R jumps it by <b>+R</b>. A pure couple does not jump shear.</p><div class="worked-result">Peak |V| = <b>${(0, common_1.fmt)(Math.abs(a.peakV.V))} kN</b> at x = <b>${(0, common_1.fmt)(a.peakV.x)} m</b><small>Signed critical value: ${(0, common_1.signed)(a.peakV.V)} kN. Checked on both sides of structural events.</small></div>`;
    if (n === 4)
        return `<h3>The shear diagram is the slope of the moment diagram.</h3><div class="formula">dM/dx = V(x)</div><p>Positive shear means increasing moment; negative shear means decreasing moment. A point force changes the slope of M, but not M itself. A positive CCW couple causes a <b>negative moment jump</b> in the adopted left-to-right internal convention.</p><p>An internal hinge releases bending moment: <b>M(H⁻) = M(H⁺) = 0</b>. Ordinary intermediate roller or pin supports do not impose zero bending moment on a continuous beam.</p><div class="worked-result">Peak |M| = <b>${(0, common_1.fmt)(Math.abs(a.peakM.M))} kN·m</b> at x = <b>${(0, common_1.fmt)(a.peakM.x)} m</b><small>Signed critical moment: ${(0, common_1.signed)(a.peakM.M)} kN·m.</small></div>`;
    return `<h3>Find the critical values mathematically.</h3><p>For moment, evaluate all event boundaries and roots of V(x) = 0 inside each region. For shear, also evaluate roots of w(x) = 0. For displacement, include stationary points where rotation is zero.</p><div class="critical-grid"><article><small>Shear / signed</small><b>${(0, common_1.signed)(a.peakV.V)} kN</b><span>x = ${(0, common_1.fmt)(a.peakV.x)} m</span></article><article><small>Moment / signed</small><b>${(0, common_1.signed)(a.peakM.M)} kN·m</b><span>x = ${(0, common_1.fmt)(a.peakM.x)} m</span></article><article><small>Displacement / up positive</small><b>${(0, common_1.signed)(a.peakD.v * 1000)} mm</b><span>x = ${(0, common_1.fmt)(a.peakD.x)} m</span></article></div><details><summary>Numerical consistency checks</summary><p>Hinge moment residual: ${a.hingeResidual.toExponential(2)} kN·m.<br>Support displacement residual: ${a.boundaryResidual.toExponential(2)} m.<br>Element end compatibility residual: ${a.endCompatibilityResidual.toExponential(2)} m.</p></details><p class="muted">These are checks on the mathematical model, not approval of the loads, support details or member strength.</p>`;
}
function working(m, a, n) {
    return `<header class="working-head"><div><span class="eyebrow">WORKED SOLUTION</span><h2>Understand every step.</h2></div><span class="tag">${n + 1} of 6</span></header><div class="steps">${exports.steps.map((s, i) => (0, common_1.button)('step:' + i, `<i>${i + 1}</i><span>${s}</span>`, n === i ? 'active' : '')).join('')}</div><div class="step-content">${workingStep(m, a, n)}</div><div class="step-footer">${(0, common_1.button)('step:' + Math.max(0, n - 1), 'Previous', 'secondary', n === 0)}<span>Calculated from the current active model</span>${(0, common_1.button)('step:' + Math.min(5, n + 1), 'Next step', 'primary', n === 5)}</div>`;
}
